spring:
  application:
    name: payment-service
  h2:
    console:
      enabled: true
  config:
    import: "configserver:http://localhost:9096"
server:
  port: 9191
  
management:
  tracing:
    sampling:
      probability: 1.0   # 100% sampling
  endpoints:
    web:
      exposure:
        include: "*"